# Generated by Django 3.2.10 on 2021-12-15 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.IntegerField()),
                ('recipent_name', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode.company')),
            ],
        ),
        migrations.CreateModel(
            name='OTPProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('barcode.otp',),
        ),
    ]
